version: "2.1"

services:
  continix:
    image: continixlabs/devenv:1.1
    volumes:
      - ./:/src
      - ~/.aws:/root/.aws
    environment:
      # - TF_LOG=TRACE
      # - PACKER_LOG=1 
      # - PACKER_LOG_PATH=packer.log
      - AWS_PROFILE=continix_dev
    
    working_dir: /src
    command: ["/bin/ash"]

  showaws:
    extends: 
      service: continix
    command: ["aws", "configure", "list"]
  
  get:
    extends:
      service: continix
    command: ["terraform", "get", "-update=true"]
  
  init:
    extends:
      service: continix
    command: ["terraform", "init", "-force-copy"]
  
  fmt:
    extends:
      service: continix
    command: ["terraform", "fmt"]
  
  pwd:
    extends:
      service: continix
    command: ["pwd"]
  
  ls:
    extends:
      service: continix
    command: ["ls"]
  
  env:
    extends:
      service: continix
    command: ["env"]

  plan:
    extends:
      service: continix
    command: ["terraform", "plan", "-no-color", "-out=plan.out"]

  apply:
    extends:
      service: continix
    command: ["terraform", "apply", "-auto-approve"]
  
  destroy:
    extends:
      service: continix
    command: ["terraform", "destroy"]
  
  output:
    extends:
      service: continix
    command: ["terraform", "output"]
  
  tfhelp:
    extends:
      service: continix
    command: ["terraform", "--help"]
  
  phelp:
    extends:
      service: continix
    command: ["packer", "--help"]

  validate:
    extends:
      service: continix
    command: ["packer", "validate"]

  build:
    extends:
      service: continix
    command: ["packer", "build", "-color=false"]

  inspect:
    extends:
      service: continix
    command: ["packer", "inspect"]

  console:
    extends:
      service: continix
    command: ["packer", "console"]

  fix:
    extends:
      service: continix
    command: ["packer", "fix"]

  hcl2_upgrade:
    extends:
      service: continix
    command: ["packer", "hcl2_upgrade"]